Category.objects.create(category='ação')
Category.objects.create(category='animação')
Category.objects.create(category='aventura')
Category.objects.create(category='comedia')
Category.objects.create(category='guerra')
Category.objects.create(category='suspense')
