from core.models import Distributor, Category, Movie
Distributor.objects.create(distributor='20th Century Fox')
Distributor.objects.create(distributor='Warner Bros.')
Distributor.objects.create(distributor='New Line Cinema')
Distributor.objects.create(distributor='Sony Pictures')
Distributor.objects.create(distributor='Universal Studios')
Distributor.objects.create(distributor='DreamWorks')
Distributor.objects.create(distributor='Columbia')
Distributor.objects.create(distributor='Lionsgate')
Distributor.objects.create(distributor='Summit Entertainment')
